// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpGA3l-WXFymI2bSTYH7iSlKKE0Mdo_0',
    appId: '1:234358892114:web:98ed4b44edc2436e93218b',
    messagingSenderId: '234358892114',
    projectId: 'location-based-social-ap-40e23',
    authDomain: 'location-based-social-ap-40e23.firebaseapp.com',
    storageBucket: 'location-based-social-ap-40e23.firebasestorage.app',
    measurementId: 'G-EBSMS90GWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Yx-309Vj6zc9LgpzmZ8ZzTkNVda-JJw',
    appId: '1:234358892114:android:92c1aff5be07fa0c93218b',
    messagingSenderId: '234358892114',
    projectId: 'location-based-social-ap-40e23',
    storageBucket: 'location-based-social-ap-40e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpbHnyePvHahzkD4aRTjToCMLMRci55w',
    appId: '1:234358892114:ios:aed7cbb28e90568393218b',
    messagingSenderId: '234358892114',
    projectId: 'location-based-social-ap-40e23',
    storageBucket: 'location-based-social-ap-40e23.firebasestorage.app',
    iosBundleId: 'com.example.geolocationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRpGA3l-WXFymI2bSTYH7iSlKKE0Mdo_0',
    appId: '1:234358892114:web:bde2ac06937f989193218b',
    messagingSenderId: '234358892114',
    projectId: 'location-based-social-ap-40e23',
    authDomain: 'location-based-social-ap-40e23.firebaseapp.com',
    storageBucket: 'location-based-social-ap-40e23.firebasestorage.app',
    measurementId: 'G-FMX8V07DK1',
  );
}
